### ISSUE TITLE
Broken with most recent babylon version.

### ISSUE THREAD

**Issue by dmueller39** [race604/react-native-viewpager#98]
Encountered this after npm install today:

```
[2:24:08 PM] <START> find dependencies
transformed 901/902 (100%)[node-haste] Encountered an error while persisting cache:
> SyntaxError: /Projects/horseshoe/node_modules/react-native-viewpager/ViewPager.js: Type annotations must come before default assignments, e.g. instead of `age = 25: number` use `age: number = 25` (244:40)
>   242 |   },
>   243 | 
> > 244 |   _getPage(pageIdx: number, loop = false: boolean) {
>       |                                         ^
>   245 |     var dataSource = this.props.dataSource;
>   246 |     var pageID = dataSource.pageIdentities[pageIdx];
>   247 |     return (
>     at Parser.pp.raise (/Projects/horseshoe/node_modules/babylon/lib/parser/location.js:22:13)
>     at Parser.parseMaybeDefault (/Projects/horseshoe/node_modules/babylon/lib/plugins/flow.js:337:14)
>     at Parser.pp.parseBindingList (/Projects/horseshoe/node_modules/babylon/lib/parser/lval.js:195:22)
>     at Parser.pp.parseMethod (/Projects/horseshoe/node_modules/babylon/lib/parser/expression.js:878:22)
>     at Parser.pp.parseObjPropValue (/Projects/horseshoe/node_modules/babylon/lib/parser/expression.js:799:10)
>     at Parser.parseObjPropValue (/Projects/horseshoe/node_modules/babylon/lib/plugins/flow.js:306:13)
>     at Parser.pp.parseObj (/Projects/horseshoe/node_modules/babylon/lib/parser/expression.js:777:10)
>     at Parser.pp.parseExprAtom (/Projects/horseshoe/node_modules/babylon/lib/parser/expression.js:481:19)
>     at Parser.parseExprAtom (/Projects/horseshoe/node_modules/babylon/lib/plugins/jsx/index.js:16:22)
>     at Parser.pp.parseExprSubscripts (/Projects/horseshoe/node_modules/babylon/lib/parser/expression.js:270:19)
```

Here is a PR to fix it: https://github.com/race604/react-native-viewpager/pull/97

**Comment by 1148030615** [comment]
改成这样吧_getPage(pageIdx: number,loop = false) {
